use crate::game::{BoardDefinition, BoardEdge, BoardNode, SideToMove, StartState};

pub const BEAR_GAME_BOARD: BoardDefinition = BoardDefinition {
    name: "Bear Game",
    turn_limit: 40,
    nodes: &[
        BoardNode {
            id: "top_left",
            x: -1,
            y: -3,
        },
        BoardNode {
            id: "top",
            x: 0,
            y: -3,
        },
        BoardNode {
            id: "top_right",
            x: 1,
            y: -3,
        },
        BoardNode {
            id: "upper_mid",
            x: 0,
            y: -2,
        },
        BoardNode {
            id: "left_outer_top",
            x: -4,
            y: 0,
        },
        BoardNode {
            id: "left_outer_mid",
            x: -4,
            y: 1,
        },
        BoardNode {
            id: "left_outer_bottom",
            x: -4,
            y: 2,
        },
        BoardNode {
            id: "left_inner",
            x: -3,
            y: 1,
        },
        BoardNode {
            id: "right_outer_top",
            x: 4,
            y: 0,
        },
        BoardNode {
            id: "right_outer_mid",
            x: 4,
            y: 1,
        },
        BoardNode {
            id: "right_outer_bottom",
            x: 4,
            y: 2,
        },
        BoardNode {
            id: "right_inner",
            x: 3,
            y: 1,
        },
        BoardNode {
            id: "bottom_left",
            x: -1,
            y: 4,
        },
        BoardNode {
            id: "bottom",
            x: 0,
            y: 4,
        },
        BoardNode {
            id: "bottom_right",
            x: 1,
            y: 4,
        },
        BoardNode {
            id: "lower_mid",
            x: 0,
            y: 3,
        },
        BoardNode {
            id: "center_top",
            x: 0,
            y: -1,
        },
        BoardNode {
            id: "center_left",
            x: -1,
            y: 1,
        },
        BoardNode {
            id: "center",
            x: 0,
            y: 1,
        },
        BoardNode {
            id: "center_right",
            x: 1,
            y: 1,
        },
        BoardNode {
            id: "center_bottom",
            x: 0,
            y: 2,
        },
    ],
    edges: &[
        BoardEdge("top_left", "top"),
        BoardEdge("top", "top_right"),
        BoardEdge("top", "upper_mid"),
        BoardEdge("top_left", "upper_mid"),
        BoardEdge("top_right", "upper_mid"),
        BoardEdge("upper_mid", "center_top"),
        BoardEdge("center_top", "center"),
        BoardEdge("center_top", "center_left"),
        BoardEdge("center_top", "center_right"),
        BoardEdge("left_outer_top", "left_outer_mid"),
        BoardEdge("left_outer_mid", "left_outer_bottom"),
        BoardEdge("left_outer_mid", "left_inner"),
        BoardEdge("left_outer_top", "left_inner"),
        BoardEdge("left_outer_bottom", "left_inner"),
        BoardEdge("left_inner", "center_left"),
        BoardEdge("center_left", "center"),
        BoardEdge("center", "center_right"),
        BoardEdge("center_right", "right_inner"),
        BoardEdge("center_left", "center_bottom"),
        BoardEdge("center", "center_bottom"),
        BoardEdge("center_right", "center_bottom"),
        BoardEdge("center_bottom", "lower_mid"),
        BoardEdge("lower_mid", "bottom"),
        BoardEdge("bottom_left", "bottom"),
        BoardEdge("bottom", "bottom_right"),
        BoardEdge("bottom_left", "lower_mid"),
        BoardEdge("bottom_right", "lower_mid"),
        BoardEdge("right_inner", "right_outer_mid"),
        BoardEdge("right_outer_top", "right_outer_mid"),
        BoardEdge("right_outer_mid", "right_outer_bottom"),
        BoardEdge("right_outer_top", "right_inner"),
        BoardEdge("right_outer_bottom", "right_inner"),
        BoardEdge("bottom_left", "left_outer_bottom"),
        BoardEdge("bottom_right", "right_outer_bottom"),
        BoardEdge("top_left", "left_outer_top"),
        BoardEdge("top_right", "right_outer_top"),
    ],
    start: StartState {
        bear: "top",
        hunters: ["bottom_left", "bottom", "bottom_right"],
        side_to_move: SideToMove::Hunters,
    },
};
